class ArgumentError(Exception):
	pass

class NotFound(Exception):
	pass